---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: verticalpodautoscalercontrollers.autoscaling.openshift.io
spec:
  group: autoscaling.openshift.io
  names:
    kind: VerticalPodAutoscalerController
    listKind: VerticalPodAutoscalerControllerList
    plural: verticalpodautoscalercontrollers
    singular: verticalpodautoscalercontroller
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              safetyMarginFraction:
                type: number
                minimum: 0
              podMinCPUMillicores:
                type: number
                minimum: 0
              podMinMemoryMb:
                type: number
                minimum: 0
              recommendationOnly:
                type: boolean
              minReplicas:
                type: number
                minimum: 1
            type: object
          status:
            type: object
        type: object
    served: true
    storage: true
